<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.itzloghotxd</groupId>
    <artifactId>enderchest</artifactId>
    <version>0.2.0-a</version>
    <packaging>jar</packaging>

    <name>EnderChest</name>

    <description>A simple ender chest plugin. Same as Hypixel Skyblock</description>
    <properties>
        <java.version>16</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <pdk.version>0.3.0</pdk.version>
    </properties>

    <url>https://modrinth.com/project/enderchestig</url>

    <developers>
        <developer>
            <id>ItzLoghotXD</id>
            <name>Loghot</name>
            <email>itzloghotxd@gmail.com</email>
        </developer>
    </developers>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <includes>
                                    <include>org.bstats</include>
                                    <include>me.itzloghotxd.pdk</include>
                                </includes>
                            </artifactSet>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <relocations>
                                <relocation>
                                    <pattern>org.bstats</pattern>
                                    <shadedPattern>${project.groupId}.${project.artifactId}.libs.bstats</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.destroystokyo.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.16.5-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-bukkit</artifactId>
            <version>3.2.1</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>me.itzloghotxd.pdk</groupId>
            <artifactId>command</artifactId>
            <version>0.3.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>me.itzloghotxd.pdk</groupId>
            <artifactId>config</artifactId>
            <version>0.3.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>me.itzloghotxd.pdk</groupId>
            <artifactId>gui</artifactId>
            <version>0.3.0</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
